### ISSUE TITLE
No module named 'torchdyn.core'

### ISSUE THREAD

**Issue by merdan-9** [DiffEqML/torchdyn#114]
Hi,

I installed torchdyn and ran the Quickstart code,  but it occurs: "ModuleNotFoundError: No module named 'torchdyn.core'".

How should I fix it?

Thanks for your help!

**Comment by Zymrael** [comment]
Which `torchdyn` version was installed?

**Comment by merdan-9** [comment]
torchdyn                  0.2.2.1                  pypi_0    pypi

**Comment by j-koch** [comment]
Having same issue - clean install in new conda environment; installed torchdyn 1.0 using pip. Attempting:
`from torchdyn.core import *`
fails with "No module names 'torchdyn.core'.

**Comment by sinhon2030** [comment]
getting the same error.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-8d99147c051a> in <module>()
----> 1 from torchdyn.core import NeuralODE

ModuleNotFoundError: No module named 'torchdyn.core'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by Zymrael** [comment]
To fix this issue upgrade your Python to `>=3.8`. Attempting to `pip install torchdyn` with a Python version `<3.8` installs `torchdyn=0.2.2.1` which was the last compatible with older Python. We've now removed `0.2.2.1` from PyPI to avoid confusion.

**Comment by rsrad** [comment]
I am using conda environment with python 3.9.1 and pip21.2.3 on Ubuntu. I did use pip install torchdyn==1.0.0 to install it. 
(1) I can import torchdyn. torchdyn.__version__ returns '1.0. 
(2) from torchdyn.datasets import * Works well 
However,
(3) from torchdyn.core import *  OR from torchdyn.core import NeuralODE 
throws error ModuleNotFoundError: No module named 'torchcde'

Please suggest

**Comment by j-koch** [comment]
@Zymrael I get the same behavior as @rsrad just reported; my conda environment is using Python 3.9.5 and pip installed torchdyn version 1.0. Importing 'datasets' or '*' works, importing torchdyn.core fails.

**Comment by Zymrael** [comment]
`torchcde` is not installed automatically in `1.0.0` since at the time it was not available on PyPI. We have now added a direct dependency so installing `torchdyn=1.0.1` will install that for you. For now you can simply `pip install torchcde`

**Comment by Zymrael** [comment]
Closing for now as the issue seems resolved.
