### ISSUE TITLE
can I modify the package somehow to make it compatible with Python 3.6?

### ISSUE THREAD

**Issue by abcde-1447** [DiffEqML/torchdyn#117]
Hi,

Thank you for this great repo!  I was trying to run this package for my research projects, and it looks like it requires Python 3.8, which is not compatible with several of packages I am using (e.g. pandas == 0.21).  I am wondering if it is possible to somehow modify this package to make it compatible with Python 3.6?

Any suggestions would be much appreciated, thank you!

**Comment by Zymrael** [comment]
This should be definitely doable. We don't extensively use any feature from the newer Python version. You might need to tinker with the dependency versions. `torchcde` and `pytorch-lightning` should both work ok since they are 3.6+.

Let me know if you encounter issues related to a specific dependency, and we'll find a workaround.

**Comment by Zymrael** [comment]
Closing as the issue seems to be fixed.
