### ISSUE TITLE
Installation problem on Colab

### ISSUE THREAD

**Issue by mrpositron** [DiffEqML/torchdyn#123]
**Could not install `torchdyn` on colab**

**Step to Reproduce**

1. Go to 'colab'
2. Run `!pip install torchdyn`
3. See the following error:
```
ERROR: Could not find a version that satisfies the requirement torchdyn (from versions: none)
ERROR: No matching distribution found for torchdyn
```

**Expected behavior**
To be able to install `torchdyn` properly.

**Screenshots**

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/42044624/147199125-d3ea40a5-36bf-4cfb-aacd-c853bf182344.png">

**Additional context**

**Comment by Zymrael** [comment]
This should be because `torchdyn` requires ver. `3.8+`  of Python and Colab runs on older versions by default. I'd suggest installing a `3.8` kernel on a Colab machine and then try to pip install again. Most of the package should work with `3.6+` as well, so you can also install directly after cloning the repo if changing Python version is not a possibility.

**Comment by mrpositron** [comment]
Okay. Got it. Thanks!
