### ISSUE TITLE
AssertionError: each element of save_at [torch.Tensor] must be contained in t_span [torch.Tensor] once and only once, why am I getting this error?

### ISSUE THREAD

**Issue by bigyaan** [DiffEqML/torchdyn#159]
My code was running fine for older version of torchdyn but I get the above error in the newer version. What has changed in this newer version?

**Comment by joglekara** [comment]
Thanks for your question!

There was a new flag added to the fixed step solver (`fixed_odeint`) to indicate at which steps you would like to save the solution. The error is telling you that the contents of whatever is being passed in as save_at are not in t_span. So it can't save that timestep and is giving you an error before running, and finding out that it didn't save the timesteps you wanted.

I'd suggest checking whether you are passing in a `save_at` tensor? If not, should you? If yes, make sure its contents are also in `t_span`.

**Comment by bigyaan** [comment]
Hello @joglekara , thank you for your answer. I understand where you are saying but can't seem to find how to fix this problem in my code.
https://colab.research.google.com/drive/1DXFkPzOPeqBBmYON3TOtxi9tHwrUmgBs?usp=sharing
This is my code could you have a look at it.

**Comment by joglekara** [comment]
I just took a look at the notebook and saw this error which is different than the assertion error you were getting earlier, so you probably have made some changes since then.

```python
TypeError: trajectory() got an unexpected keyword argument 'save_at'
```
Unfortunately, I can't access the data in your notebook so I can't fully debug it 

I would try not passing in `save_at` to the trajectory call you have in your LSTM. `trajectory` should just output every timestep in `t_span`.

We can debug over slack if you want, it might be a little easier/faster.

**Comment by bigyaan** [comment]
@joglekara Hello, thanks lot. I would be delighted if we could do it over slack. I think I am added to this repos slack

**Comment by bigyaan** [comment]
@joglekara hey there, I solved this problem. The atol and rtol of isclose was 1e-3 in default. However, my time span value was in 1e5, this made the function to give strange results. I reduced the representation of value to 3 digits and it worked fine. Thank you for your effort.
