### ISSUE TITLE
Can we talk about stable neural flows?

### ISSUE THREAD

**Issue by RobWalt** [DiffEqML/torchdyn#76]
I don't understand the theoretical part of the paper [stable neural flows](https://arxiv.org/pdf/2003.08063.pdf) and I think there might be something wrong with it.

Can someone explain the proof of Proposition 1 in detail?

If there won't be any answers, I suggest to precautionary remove the stable model.

**Comment by massastrello** [comment]
Hi Robert!

If could be more detailed about which step of the proof you do not understand we can provide you a specific answer. 

The result you mentioned follows directly from Lyapunov 2nd Theorem and the class assumptions on the function $\epsilon$. Stability of sets is a classic and well-studied property of nonlinear system and control (ubiquitous in the field of "hybrid systems", see e.g. Th. 20 in  https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4806347).   

Since you did not specify your background or level of expertise in the field I may suggest Chapter 4 of Khalil, H. _Nonlinear systems_  for some basic results on Lyapunov stability as well as more technical readings on set stability
https://folk.ntnu.no/rskjetne/Publications/2004-8-W%20NTNU%20-%20Skjetne%20-%20SetStabilityTheory.pdf
https://hal.inria.fr/hal-00745623/document

If you want to have in-depth discussions or you have some findings on _Stable Neural Flows_, I encourage you to DM me and Michael at massaroli@robot.t.u-tokyo.ac.jp  and poli@stanford.edu

**Comment by RobWalt** [comment]
Thanks for the reply. At the moment I'm convinced everything is right and I'm happy with the sources you provided but I need to think it through thoroughly again.

Maybe it would be a good idea to include a pointer to the book of Khalil in the paper or state which theorem is used in the proposition (I guess it's LaSalle's theorem).

Also it was kind of hard to reach you. I didn't want to open a github issue, but the emails I already sent didn't came through to you.

**Comment by Zymrael** [comment]
Thank you for reaching out.
